[workspace]
authors = ["Ethan Littlestone <ethanlittlestone@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "sc_rna_seq_analysis"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
snakemake = ">=9.5.1,<10"
entrez-direct = ">=22.4,<23"
geofetch = ">=0.12.7,<0.13"
sra-tools = ">=3.2.1,<4"
trimmomatic = ">=0.39,<0.40"
fastqc = ">=0.12.1,<0.13"
multiqc = ">=1.29,<2"
ncbi-datasets-cli = ">=18.2.0,<19"
tmux = ">=3.5,<4"
eza = ">=0.21.3,<0.22"
ruby = ">=3.4.2,<4"
nvim = "0.9.*"
rust = ">=1.87.0,<1.88"
nodejs = ">=18"
ripgrep = ">=14.1.1,<15"
lazygit = ">=0.51.1,<0.52"
git = ">=2.49.0,<3"
gcc = ">=15.1.0,<15.2"
ffq = ">=0.3.1,<0.4"
