[workspace]
authors = ["Ethan Littlestone <ethanlittlestone@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "sc_rna_seq_analysis"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
snakemake = ">=9.5.1,<10"
entrez-direct = ">=22.4,<23"
geofetch = ">=0.12.7,<0.13"
#sra-tools = ">=3.2.1,<4"
trimmomatic = ">=0.39,<0.40"
fastqc = ">=0.12.1,<0.13"
multiqc = ">=1.29,<2"
ncbi-datasets-cli = ">=18.2.0,<19"
tmux = ">=3.5,<4"
eza = ">=0.21.3,<0.22"
ruby = ">=3.4.2,<4"
rust = ">=1.87.0,<1.88"
nodejs = ">=18"
ripgrep = ">=14.1.1,<15"
lazygit = ">=0.51.1,<0.52"
git = ">=2.49.0,<3"
#gcc = ">=15.1.0,<15.2"
ffq = ">=0.3.1,<0.4"
cellxgene = ">=1.3.0,<2"
anndata = ">=0.11.4,<0.12"
scanpy = ">=1.11.1,<2"
git-lfs = ">=3.6.1,<4"
nbclient = ">=0.10.2,<0.11"
scikit-image = ">=0.25.2,<0.26"
openssl = ">=3.5.0,<4"
igraph = ">=0.10.15,<0.11"
python-igraph = ">=0.11.8,<0.12"
leidenalg = ">=0.10.2,<0.11"
scrublet = ">=0.2.3,<0.3"
pandas = ">=2.2.3,<3"
