[workspace]
authors = ["Ethan Littlestone <ethanlittlestone@gmail.com>"]
channels = ["conda-forge", "bioconda", "hcc", "dranew"]
name = "sc_rna_seq_analysis"
platforms = ["osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
snakemake = ">=9.5.1,<10"
entrez-direct = ">=22.4,<23"
geofetch = ">=0.12.7,<0.13"
sra-tools = ">=3.2.1,<4"
trimmomatic = ">=0.39,<0.40"
fastqc = ">=0.12.1,<0.13"
multiqc = ">=1.29,<2"
ncbi-datasets-cli = ">=18.2.0,<19"
aspera-cli = { version = ">=3.9.6,<4", channel = "hcc" }
ffq = ">=0.3.1,<0.4"
